github: oseelabs  # your GitHub username
#patreon: yourPatreon
#open_collective: yourCollective
ko_fi: lazaroodira
custom: [https://www.paypal.com/ncp/payment/CRMQJNC2CAYMU', 'https://paypal.me/lazaroosee']
